mcu_adc::
	gcc -o main -DMCU_ADC main.c adc_measurement_task.c mcu_adc.c spi_adc.c voltage_sender.c
spi_adc::
	gcc -o main -DSPI_ADC main.c adc_measurement_task.c mcu_adc.c spi_adc.c voltage_sender.c

phony: mcu_adc spi_adc

